# vim:ft=kitty

## name:     Rosé Pine

# The basic colors
foreground              #e0def4
background              #191724
selection_foreground    #e0def4
selection_background    #403d52

# Cursor colors
cursor                  #e0def4
cursor_text_color       #191724

# Scrollbar colors
scrollbar_handle_color  #6e6a86
scrollbar_track_color   #1f1d2e

# URL color when hovering with mouse
url_color               #9ccfd8

# Kitty window border colors
active_border_color     #c4a7e7
inactive_border_color   #1f1d2e
bell_border_color       #f6c177

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #191724
active_tab_background   #c4a7e7
inactive_tab_foreground #6e6a86
inactive_tab_background #1f1d2e
tab_bar_background      #26233a

# Colors for marks (marked text in the terminal)
mark1_foreground #191724
mark1_background #9ccfd8
mark2_foreground #191724
mark2_background #c4a7e7
mark3_foreground #191724
mark3_background #ebbcba

# The 16 terminal colors

# black
color0 #26233a
color8 #6e6a86

# red
color1 #eb6f92
color9 #eb6f92

# green
color2  #31748f
color10 #31748f

# yellow
color3  #f6c177
color11 #f6c177

# blue
color4  #9ccfd8
color12 #9ccfd8

# magenta
color5  #c4a7e7
color13 #c4a7e7

# cyan
color6  #ebbcba
color14 #ebbcba

# white
color7  #e0def4
color15 #e0def4
