# vim:ft=kitty

## name:     Rosé Pine Dawn

# The basic colors
foreground              #464261
background              #faf4ed
selection_foreground    #464261
selection_background    #dfdad9

# Cursor colors
cursor                  #464261
cursor_text_color       #faf4ed

# Scrollbar colors
scrollbar_handle_color  #9893a5
scrollbar_track_color   #fffaf3

# URL color when hovering with mouse
url_color               #56949f

# Kitty window border colors
active_border_color     #907aa9
inactive_border_color   #fffaf3
bell_border_color       #ea9d34

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #faf4ed
active_tab_background   #907aa9
inactive_tab_foreground #9893a5
inactive_tab_background #fffaf3
tab_bar_background      #f2e9e1

# Colors for marks (marked text in the terminal)
mark1_foreground #faf4ed
mark1_background #56949f
mark2_foreground #faf4ed
mark2_background #907aa9
mark3_foreground #faf4ed
mark3_background #d7827e

# The 16 terminal colors

# black
color0 #f2e9e1
color8 #9893a5

# red
color1 #b4637a
color9 #b4637a

# green
color2  #286983
color10 #286983

# yellow
color3  #ea9d34
color11 #ea9d34

# blue
color4  #56949f
color12 #56949f

# magenta
color5  #907aa9
color13 #907aa9

# cyan
color6  #d7827e
color14 #d7827e

# white
color7  #464261
color15 #464261
