# =============================================================================
# 💥 LAZYGIT CONFIG — Git, But Smarter & Safer
# A focused, beginner-friendly UI that grows with your Git mastery.
# Optimized for clarity, safety, and speed—no surprises, just flow.
# =============================================================================

gui:
  # 🎨 UI & Navigation
  scrollHeight: 3
  scrollPastBottom: false
  scrollOffMargin: 1
  scrollOffBehavior: margin
  tabWidth: 2
  mouseEvents: false            # Better text selection; use keyboard nav
  sidePanelWidth: 0.35
  expandFocusedSidePanel: true
  mainPanelSplitMode: flexible
  enlargedSideViewLocation: left
  wrapLinesInStagingView: true
  useHunkModeInStagingView: true
  language: auto
  timeFormat: "02 Jan 06"
  shortTimeFormat: "15:04"      # 24h format → cleaner, no AM/PM

  # 🎨 Theme — Clean, high-contrast, distraction-free
  theme:
    activeBorderColor:
      - "#00ffaa"
      - bold
    inactiveBorderColor:
      - "#555555"
    searchingActiveBorderColor:
      - "#00ccff"
      - bold
    optionsTextColor:
      - "#00ccff"
    selectedLineBgColor:
      - "#2a2a2a"
    inactiveViewSelectedLineBgColor:
      - "#3a3a3a"
    unstagedChangesColor:
      - "#ff5555"
    defaultFgColor:
      - default

  # 🖼️ Layout & Info Density
  showFileTree: true
  showRootItemInFileTree: true
  showNumstatInFilesView: true   # See +/− lines per file
  showListFooter: true
  showCommandLog: true
  showBottomLine: true
  showPanelJumps: true
  nerdFontsVersion: ""           # No icons → pure speed & compatibility
  showFileIcons: false
  commitAuthorShortLength: 1     # Just first initial
  commitAuthorLongLength: 15
  commitHashLength: 7
  showBranchCommitHash: false
  showDivergenceFromBaseBranch: arrowAndNumber
  commandLogSize: 6
  splitDiff: auto
  screenMode: normal
  border: single                 # Cleaner than rounded
  animateExplosion: false        # Less distraction
  portraitMode: auto
  filterMode: fuzzy              # Smarter search: `feat` matches `feature/login`

  # ⚙️ UX Safety & Flow
  skipAmendWarning: false
  skipDiscardChangeWarning: false
  skipStashWarning: false
  skipNoStagedFilesWarning: false
  skipRewordInEditorWarning: false
  skipSwitchWorktreeOnCheckoutWarning: false
  switchToFilesAfterStashPop: true
  switchToFilesAfterStashApply: true
  switchTabsWithPanelJumpKeys: false

  # 🌀 Spinner (subtle)
  spinner:
    frames: ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"]
    rate: 80

  statusPanelView: dashboard

# 📦 Git Behavior — Smart defaults
git:
  # 📜 Committing
  commit:
    signOff: false
    autoWrapCommitMessage: true
    autoWrapWidth: 72

  # 🔄 Merging & Branches
  merging:
    manualCommit: false
    args: ""
    squashMergeMessage: "Squash: {{selectedRef}} → {{currentBranch}}"

  mainBranches:
    - main
    - master
    - develop

  skipHookPrefix: "WIP"

  # 🔄 Auto-sync (safe & useful)
  autoFetch: true
  autoRefresh: true
  autoForwardBranches: onlyMainBranches
  fetchAll: true
  autoStageResolvedConflicts: true

  # 📊 Log & Graph
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
  allBranchesLogCmds:
    - git log --graph --all --color=always --abbrev-commit --decorate --date=relative --pretty=medium

  ignoreWhitespaceInDiffView: false
  diffContextSize: 3
  renameSimilarityThreshold: 50

  log:
    order: topo-order
    showGraph: always
    showWholeGraph: false

  localBranchSortOrder: recency     # Most recently used first
  remoteBranchSortOrder: date

  truncateCopiedCommitHashesTo: 10

  # 🛑 Safety
  disableForcePushing: false
  overrideGpg: false

# 🖥️ OS Integration — Customize based on your system
os:
  # 🔧 Edit commands — UNCOMMENT & SET YOUR EDITOR
  edit: "code -r {{filename}}"
  # edit: "nvim {{filename}}"
  # editAtLine: "nvim +{{line}} {{filename}}"
  # editAtLineAndWait: "nvim +{{line}} {{filename}}"
  # editInTerminal: true
  # open: "xdg-open {{filename}}"     # Linux
  # open: "open {{filename}}"         # macOS
  # openLink: "xdg-open {{link}}"     # Linux
  # openLink: "open {{link}}"         # macOS

  # 📋 Clipboard (Linux example)
  # copyToClipboardCmd: "wl-copy"     # Wayland
  # copyToClipboardCmd: "xclip -selection clipboard"  # X11
  # readFromClipboardCmd: "wl-paste"
  # readFromClipboardCmd: "xclip -selection clipboard -o"

# 🔁 Background & Updates
refresher:
  refreshInterval: 10
  fetchInterval: 60

update:
  method: background   # Check silently
  days: 7

# 🛑 Quit behavior
confirmOnQuit: true
quitOnTopLevelReturn: false

# 🚫 No startup popups
disableStartupPopups: true

# 🎯 Keybindings — Keep defaults (they’re great!)
# Only override if you *really* need to
keybinding: {}
