# Rosé Pine Moon for Helix Editor

attribute = "purple"
keyword = "orange"
"keyword.directive" = "purple"
namespace = "yellow"
punctuation = "grey1"
"punctuation.delimiter" = "grey1"
operator = "orange"
special = "aqua"
"variable.other.member" = "blue"
variable = "blue"
"variable.parameter" = { fg = "blue" }
"variable.builtin" = "aqua"
type = "yellow"
"type.builtin" = "yellow"
constructor = "yellow"
function = "green"
"function.macro" = "aqua"
"function.builtin" = "green"
tag = "orange"
comment = "grey1"
constant = "aqua"
"constant.builtin" = "aqua"
string = "green"
"constant.numeric" = "purple"
"constant.character.escape" = "aqua"
label = "aqua"

# Markup
"markup.heading" = "orange"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "blue", modifiers = ["underlined"] }
"markup.link.text" = "aqua"
"markup.raw" = "green"

# Diff
"diff.plus" = { fg = "green", bg = "bg_green" }
"diff.minus" = { fg = "red", bg = "bg_red" }
"diff.delta" = { fg = "blue", bg = "bg_blue" }

# UI
"ui.background" = { bg = "bg0" }
"ui.background.separator" = { fg = "grey1" }
"ui.linenr" = { fg = "grey0" }
"ui.linenr.selected" = { fg = "grey2" }
"ui.statusline" = { fg = "bg0", bg = "green" }
"ui.statusline.inactive" = { fg = "grey1", bg = "bg3" }
"ui.popup" = { bg = "bg2" }
"ui.window" = { fg = "bg3" }
"ui.help" = { bg = "bg2", fg = "fg" }
"ui.text" = { fg = "fg" }
"ui.text.focus" = { fg = "fg" }
"ui.text.inactive" = "grey1"
"ui.text.directory" = { fg = "blue" }
"ui.virtual" = { fg = "grey1" }
"ui.virtual.ruler" = { bg = "bg1" }
"ui.virtual.jump-label" = { fg = "orange", modifiers = ["bold"] }
"ui.virtual.indent-guide" = { fg = "bg3" }

# Selection & Cursor
"ui.selection" = { bg = "bg_visual" }
"ui.selection.primary" = { bg = "bg_visual" }
"ui.cursor.select" = { bg = "bg_visual" }
"ui.cursor.insert" = { bg = "grey2" }
"ui.cursor.primary.select" = { bg = "bg_visual" }
"ui.cursor.primary.insert" = { bg = "grey2" }
"ui.cursor.match" = { fg = "bg0", bg = "green" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursorline.primary" = { bg = "bg1" }
"ui.highlight" = { bg = "bg1" }
"ui.highlight.frameline" = { bg = "bg_red" }
"ui.debug" = { fg = "red" }
"ui.debug.breakpoint" = { fg = "red" }
"ui.menu" = { fg = "fg", bg = "bg2" }
"ui.menu.selected" = { fg = "bg0", bg = "green" }
"ui.menu.scroll" = { fg = "grey1", bg = "bg3" }

# Diagnostics
"diagnostic.hint" = { underline = { color = "aqua", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

# Diagnostic Shortcuts
warning = "yellow"
error = "red"
info = "blue"
hint = "aqua"

# Palette Definition
[palette]
bg_dim = "#232136"
bg0 = "#232136"
bg1 = "#2a273f"
bg2 = "#393552"
bg3 = "#44415a"
bg4 = "#56526e"
bg_visual = "#44415a"
bg_red = "#3a2831"
bg_yellow = "#3b3530"
bg_green = "#28363d"
bg_blue = "#283640"

fg = "#e0def4"
red = "#eb6f92"
orange = "#ea9a97"
yellow = "#f6c177"
green = "#3e8fb0"
aqua = "#9ccfd8"
blue = "#3e8fb0"
purple = "#c4a7e7"
grey0 = "#6e6a86"
grey1 = "#908caa"
grey2 = "#56526e"
