"$schema" = 'https://starship.rs/config-schema.json'

# --- CORE CONFIG ---
add_newline = true
scan_timeout = 10
command_timeout = 500

format = """
$os$directory$git_branch$git_status$git_state$fill$python$nodejs$bun$cmd_duration
$character"""

# --- SYSTEM & SHELL ---
[character]
success_symbol = "[❯](cyan)[❯](green)"
error_symbol = "[❯](red)[❯](yellow)"
vicmd_symbol = "[❮](magenta)[❮](purple)"

[directory]
style = "bold cyan"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"

[directory.substitutions]
"~/Downloads" = "󰉍 "
"~/Documents/projects" = "󰴉 "

[fill]
symbol = " "
style = "bold gray"

[cmd_duration]
min_time = 2000
format = "[󱎫 $duration](bold yellow)"

# --- GIT ---
[git_branch]
symbol = "󰊢 "
style = "bold magenta"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold red"
format = '''([\[$all_status$ahead_behind\]]($style) )'''

[git_state]
style = "bold yellow"
format = '''([$state( $progress_current/$progress_total)]($style) )'''

# --- LANGUAGES ---
[python]
symbol = "󱔎 "
style = "bold blue"
format = '''[$symbol($version )(\($virtualenv\) )]($style)'''

[nodejs]
symbol = "󰎙 "
style = "bold green"
format = "[$symbol($version )]($style)"

[bun]
symbol = "󰛦 "
style = "bold white"
format = "[$symbol($version )]($style)"

# --- CLOUD & VIRTUALIZATION ---
[aws]
symbol = "󰅟 "
style = "bold yellow"
format = "[$symbol($profile )]($style)"

[docker_context]
symbol = "󰡨 "
style = "bold blue"
format = "[$symbol$context]($style) "

[kubernetes]
symbol = "󱃾 "
style = "bold cyan"
format = '''[$symbol$context( \($namespace\))]($style) '''
