# Rosé Pine Dawn for btop

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#faf4ed"

# Main text color
theme[main_fg]="#464261"

# Title color for boxes
theme[title]="#464261"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#907aa9"

# Background color of selected item in processes box
theme[selected_bg]="#907aa9"

# Foreground color of selected item in processes box
theme[selected_fg]="#faf4ed"

# Color of inactive/disabled text
theme[inactive_fg]="#9893a5"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#464261"

# Background color of the percentage meters
theme[meter_bg]="#dfdad9"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#907aa9"

# Cpu box outline color
theme[cpu_box]="#907aa9"

# Memory/disks box outline color
theme[mem_box]="#56949f"

# Net up/down box outline color
theme[net_box]="#b4637a"

# Processes box outline color
theme[proc_box]="#ea9d34"

# Box divider line and small boxes line color
theme[div_line]="#dfdad9"

# Temperature graph colors
theme[temp_start]="#b4637a"
theme[temp_mid]="#ea9d34"
theme[temp_end]="#d7827e"

# CPU graph colors
theme[cpu_start]="#907aa9"
theme[cpu_mid]="#56949f"
theme[cpu_end]="#286983"

# Mem/Disk free meter
theme[free_start]="#d7827e"
theme[free_mid]="#b4637a"
theme[free_end]="#907aa9"

# Mem/Disk cached meter
theme[cached_start]="#56949f"
theme[cached_mid]="#286983"
theme[cached_end]="#9893a5"

# Mem/Disk available meter
theme[available_start]="#ea9d34"
theme[available_mid]="#d7827e"
theme[available_end]="#b4637a"

# Mem/Disk used meter
theme[used_start]="#286983"
theme[used_mid]="#56949f"
theme[used_end]="#907aa9"

# Download graph colors
theme[download_start]="#907aa9"
theme[download_mid]="#56949f"
theme[download_end]="#286983"

# Upload graph colors
theme[upload_start]="#b4637a"
theme[upload_mid]="#d7827e"
theme[upload_end]="#ea9d34"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#56949f"
theme[process_mid]="#286983"
theme[process_end]="#9893a5"
