# Rosé Pine Moon for btop

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#232136"

# Main text color
theme[main_fg]="#e0def4"

# Title color for boxes
theme[title]="#e0def4"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#c4a7e7"

# Background color of selected item in processes box
theme[selected_bg]="#c4a7e7"

# Foreground color of selected item in processes box
theme[selected_fg]="#232136"

# Color of inactive/disabled text
theme[inactive_fg]="#6e6a86"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#e0def4"

# Background color of the percentage meters
theme[meter_bg]="#44415a"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#c4a7e7"

# Cpu box outline color
theme[cpu_box]="#c4a7e7"

# Memory/disks box outline color
theme[mem_box]="#9ccfd8"

# Net up/down box outline color
theme[net_box]="#eb6f92"

# Processes box outline color
theme[proc_box]="#f6c177"

# Box divider line and small boxes line color
theme[div_line]="#44415a"

# Temperature graph colors
theme[temp_start]="#eb6f92"
theme[temp_mid]="#f6c177"
theme[temp_end]="#ea9a97"

# CPU graph colors
theme[cpu_start]="#c4a7e7"
theme[cpu_mid]="#9ccfd8"
theme[cpu_end]="#3e8fb0"

# Mem/Disk free meter
theme[free_start]="#ea9a97"
theme[free_mid]="#eb6f92"
theme[free_end]="#c4a7e7"

# Mem/Disk cached meter
theme[cached_start]="#9ccfd8"
theme[cached_mid]="#3e8fb0"
theme[cached_end]="#6e6a86"

# Mem/Disk available meter
theme[available_start]="#f6c177"
theme[available_mid]="#ea9a97"
theme[available_end]="#eb6f92"

# Mem/Disk used meter
theme[used_start]="#3e8fb0"
theme[used_mid]="#9ccfd8"
theme[used_end]="#c4a7e7"

# Download graph colors
theme[download_start]="#c4a7e7"
theme[download_mid]="#9ccfd8"
theme[download_end]="#3e8fb0"

# Upload graph colors
theme[upload_start]="#eb6f92"
theme[upload_mid]="#ea9a97"
theme[upload_end]="#f6c177"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#9ccfd8"
theme[process_mid]="#3e8fb0"
theme[process_end]="#6e6a86"
