[colors.primary]
background = "#FDF6E3"
foreground = "#5C6A72"
dim_foreground = "#939F91"
bright_foreground = "#5C6A72"

[colors.cursor]
text = "#FDF6E3"
cursor = "#5C6A72"

[colors.vi_mode_cursor]
text = "#FDF6E3"
cursor = "#8DA101"

[colors.search.matches]
foreground = "#FDF6E3"
background = "#939F91"

[colors.search.focused_match]
foreground = "#FDF6E3"
background = "#8DA101"

[colors.hints.start]
foreground = "#FDF6E3"
background = "#F57D26"

[colors.hints.end]
foreground = "#5C6A72"
background = "#E6E2CC"

[colors.selection]
text = "#5C6A72"
background = "#EAEDC8"

[colors.normal]
black = "#5C6A72"
red = "#F85552"
green = "#8DA101"
yellow = "#DFA000"
blue = "#3A94C5"
magenta = "#DF69BA"
cyan = "#35A77C"
white = "#939F91"

[colors.bright]
black = "#829181"
red = "#F85552"
green = "#8DA101"
yellow = "#DFA000"
blue = "#3A94C5"
magenta = "#DF69BA"
cyan = "#35A77C"
white = "#5C6A72"

[[colors.indexed_colors]]
index = 16
color = "#F57D26"

[[colors.indexed_colors]]
index = 17
color = "#5C6A72"
