# Gruvbox Material Light (Medium Contrast, Material Palette)
# Author: Ashik (based on sainnhe/gruvbox-material)

[colors.primary]
background = "#fbf1c7"
foreground = "#654735"
dim_foreground = "#928374"
bright_foreground = "#4f3829"

[colors.cursor]
text = "#fbf1c7"
cursor = "#6c782e"

[colors.vi_mode_cursor]
text = "#fbf1c7"
cursor = "#b47109"

[colors.search.matches]
foreground = "#fbf1c7"
background = "#fae7b3"

[colors.search.focused_match]
foreground = "#fbf1c7"
background = "#dee2b6"

[colors.hints.start]
foreground = "#fbf1c7"
background = "#c35e0a"

[colors.hints.end]
foreground = "#654735"
background = "#eee0b7"

[colors.selection]
text = "#654735"
background = "#eee0b7"

[colors.normal]
black = "#f4e8be"
red = "#c14a4a"
green = "#6c782e"
yellow = "#b47109"
blue = "#45707a"
magenta = "#945e80"
cyan = "#4c7a5d"
white = "#654735"

[colors.bright]
black = "#a89984"
red = "#c14a4a"
green = "#6c782e"
yellow = "#b47109"
blue = "#45707a"
magenta = "#945e80"
cyan = "#4c7a5d"
white = "#4f3829"

[colors.dim]
black = "#ebdbb2"
red = "#a13a3a"
green = "#566024"
yellow = "#945c07"
blue = "#355860"
magenta = "#774b66"
cyan = "#3d624a"
white = "#928374"

[[colors.indexed_colors]]
index = 16
color = "#c35e0a"

[[colors.indexed_colors]]
index = 17
color = "#4f3829"
