# Nord Light Theme for Alacritty
# Author: Ashik

[colors.primary]
background = "#ECEFF4"
foreground = "#2E3440"
dim_foreground = "#4C566A"
bright_foreground = "#2E3440"

[colors.cursor]
text = "#ECEFF4"
cursor = "#2E3440"

[colors.vi_mode_cursor]
text = "#ECEFF4"
cursor = "#D08770"

[colors.search.matches]
foreground = "#ECEFF4"
background = "#5E81AC"

[colors.search.focused_match]
foreground = "#ECEFF4"
background = "#D08770"

[colors.hints.start]
foreground = "#ECEFF4"
background = "#D08770"

[colors.hints.end]
foreground = "#2E3440"
background = "#D8DEE9"

[colors.selection]
text = "#2E3440"
background = "#D8DEE9"

[colors.normal]
black = "#3B4252"
red = "#BF616A"
green = "#A3BE8C"
yellow = "#D08770"
blue = "#5E81AC"
magenta = "#B48EAD"
cyan = "#81A1C1"
white = "#4C566A"

[colors.bright]
black = "#4C566A"
red = "#BF616A"
green = "#A3BE8C"
yellow = "#D08770"
blue = "#5E81AC"
magenta = "#B48EAD"
cyan = "#8FBCBB"
white = "#2E3440"

[[colors.indexed_colors]]
index = 16
color = "#D08770"

[[colors.indexed_colors]]
index = 17
color = "#8FBCBB"
